<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<style>

table {border-collapse: collapse;}
table td {padding: 0px}
</style>
</head>
<body>
<div style="position:absolute;top:1.40in;left:3.07in;width:0.70in;line-height:0.25in;"><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Amiri;color:#4b6a87">#name#</span><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Amiri;color:#4b6a87"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.84in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min1#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.84in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:4.84in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std1#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.84in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:4.84in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max1#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.05in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min2#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.05in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.05in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std2#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.05in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.05in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max2#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.37in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min3#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.37in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.37in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std3#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.37in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.37in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max3#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.63in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min4#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.63in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.63in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std4#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.63in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.63in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max4#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.83in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min5#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.83in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.83in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std5#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:5.83in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:5.83in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max5#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.12in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min6#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.12in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:6.12in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std6#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.12in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:6.12in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max6#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.55in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min7#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.55in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:6.55in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std7#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.55in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:6.55in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max7#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.02in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min8#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.02in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:7.02in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std8#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.02in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:7.02in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max8#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.51in;left:4.66in;width:0.58in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min9#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.51in;left:6.01in;width:0.55in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:7.51in;left:6.01in;width:0.55in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std9#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.51in;left:7.23in;width:0.65in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:7.51in;left:7.23in;width:0.65in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max9#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.84in;left:4.55in;width:0.67in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min10#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.84in;left:5.92in;width:0.64in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:7.84in;left:5.92in;width:0.64in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std10#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:7.84in;left:7.14in;width:0.74in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:7.84in;left:7.14in;width:0.74in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max10#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.19in;left:4.55in;width:0.67in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min11#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.19in;left:5.92in;width:0.64in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:8.19in;left:5.92in;width:0.64in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std11#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.19in;left:7.14in;width:0.74in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:8.19in;left:7.14in;width:0.74in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max11#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.56in;left:4.57in;width:0.67in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min12#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.56in;left:5.92in;width:0.64in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:8.56in;left:5.92in;width:0.64in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std12#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.56in;left:7.14in;width:0.74in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:8.56in;left:7.14in;width:0.74in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max12#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.01in;left:4.57in;width:0.67in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min13#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.01in;left:5.92in;width:0.64in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:9.01in;left:5.92in;width:0.64in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std13#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.01in;left:7.14in;width:0.74in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:9.01in;left:7.14in;width:0.74in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max13#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.45in;left:4.57in;width:0.67in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#min14#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.75in;left:5.66in;width:0.53in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#total#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.45in;left:5.92in;width:0.64in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:9.45in;left:5.92in;width:0.64in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#std14#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:9.45in;left:7.14in;width:0.74in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span></SPAN><br/></div>
<div style="position:absolute;top:9.45in;left:7.14in;width:0.74in;line-height:0.21in;"><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666">#max14#</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:1.83in;left:3.07in;width:1.52in;line-height:0.25in;"><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Amiri;color:#4b6a87">#typeoﬁpwork#</span><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Amiri;color:#4b6a87"></span><br/></SPAN></div>
<div style="position:absolute;top:2.24in;left:3.07in;width:1.62in;line-height:0.25in;"><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Amiri;color:#4b6a87">#nameoﬁpwork#</span><span style="font-style:normal;font-weight:bold;font-size:13pt;font-family:Amiri;color:#4b6a87"></span><br/></SPAN></div>
<img style="position:absolute;top:2.90in;left:1.58in;width:5.84in;height:0.17in" src="ci_60.png" />
<div style="position:absolute;top:1.04in;left:0.40in;width:8.32in;line-height:0.34in;"><span style="font-style:normal;font-weight:bold;font-size:19pt;font-family:Copperplate;color:#092f56">VALUATION </span></SPAN><br/></div>
<div style="position:absolute;top:1.04in;left:0.40in;width:8.32in;line-height:0.34in;"><DIV style="position:relative; left:2.03in;"><span style="font-style:normal;font-weight:bold;font-size:19pt;font-family:Copperplate;color:#092f56">CERTIFICATE </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.04in;left:0.40in;width:8.32in;line-height:0.34in;"><DIV style="position:relative; left:4.28in;"><span style="font-style:normal;font-weight:bold;font-size:19pt;font-family:Copperplate;color:#092f56">ASSESSMENT </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:1.04in;left:0.40in;width:8.32in;line-height:0.34in;"><DIV style="position:relative; left:6.56in;"><span style="font-style:normal;font-weight:bold;font-size:19pt;font-family:Copperplate;color:#092f56">SUMMARY</span><span style="font-style:normal;font-weight:bold;font-size:19pt;font-family:Copperplate;color:#092f56"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:4.35in;left:1.09in;width:6.84in;height:5.54in" src="ci_61.png" />
<img style="position:absolute;top:3.25in;left:3.36in;width:1.90in;height:0.10in" src="ci_62.png" />
<img style="position:absolute;top:3.47in;left:3.31in;width:1.95in;height:0.12in" src="ci_63.png" />
<img style="position:absolute;top:3.69in;left:3.54in;width:1.71in;height:0.12in" src="ci_64.png" />
<img style="position:absolute;top:3.92in;left:3.66in;width:1.60in;height:0.12in" src="ci_65.png" />
<img style="position:absolute;top:4.14in;left:2.56in;width:2.70in;height:0.12in" src="ci_66.png" />
<div style="position:absolute;top:3.04in;left:5.35in;width:1.38in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057">#years#</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.27in;left:5.35in;width:1.38in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057"> #totalsalarymonthly#</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057">#totalsalesmonthly#</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.71in;left:5.35in;width:1.38in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057"> #totalsalesmonthly#</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.93in;left:5.35in;width:1.76in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057">#totalmktbudgetmonthly#</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.40in;left:5.80in;width:0.27in;height:0.07in" src="ci_67.png" />
<img style="position:absolute;top:11.44in;left:1.54in;width:0.68in;height:0.68in" src="ri_4.png" />
<div style="position:absolute;top:12.11in;left:1.32in;width:1.14in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#0c3257">Download </span></SPAN><br/></div>
<div style="position:absolute;top:12.11in;left:1.32in;width:1.14in;line-height:0.14in;"><DIV style="position:relative; left:0.53in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#0c3257">PDF </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.11in;left:1.32in;width:1.14in;line-height:0.14in;"><DIV style="position:relative; left:0.77in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#0c3257">Report</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#0c3257"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:10.98in;left:1.07in;width:1.62in;height:0.19in" src="ci_68.png" />
<div style="position:absolute;top:11.00in;left:1.37in;width:1.05in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Copperplate;color:#ffffff">UNIVERSAL</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Copperplate;color:#ffffff"> </span><br/></SPAN></div>
<img style="position:absolute;top:11.17in;left:1.07in;width:1.62in;height:0.19in" src="ci_69.png" />
<img style="position:absolute;top:11.17in;left:1.07in;width:1.62in;height:0.19in" src="ci_70.png" />
<div style="position:absolute;top:11.20in;left:1.53in;width:0.73in;line-height:0.14in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#092f56">Free </span></SPAN><br/></div>
<div style="position:absolute;top:11.20in;left:1.53in;width:0.73in;line-height:0.14in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#092f56">of </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.20in;left:1.53in;width:0.73in;line-height:0.14in;"><DIV style="position:relative; left:0.36in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#092f56"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.20in;left:1.53in;width:0.73in;line-height:0.14in;"><DIV style="position:relative; left:0.39in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#092f56">charge</span><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#092f56"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:10.98in;left:3.70in;width:1.62in;height:0.19in" src="ci_71.png" />
<img style="position:absolute;top:11.17in;left:3.70in;width:1.62in;height:0.19in" src="ci_72.png" />
<img style="position:absolute;top:11.17in;left:3.70in;width:1.62in;height:0.19in" src="ci_73.png" />
<div style="position:absolute;top:12.07in;left:3.84in;width:1.37in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">Upgrade</span></SPAN><br/></div>
<div style="position:absolute;top:12.07in;left:3.84in;width:1.37in;line-height:0.14in;"><DIV style="position:relative; left:0.39in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.07in;left:3.84in;width:1.37in;line-height:0.14in;"><DIV style="position:relative; left:0.42in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">to </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.07in;left:3.84in;width:1.37in;line-height:0.14in;"><DIV style="position:relative; left:0.54in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">Validation </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.07in;left:3.84in;width:1.37in;line-height:0.14in;"><DIV style="position:relative; left:1.03in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">(KYC)</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.98in;left:4.05in;width:0.97in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Copperplate;color:#ffffff">validation</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Copperplate;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.20in;left:3.97in;width:1.10in;line-height:0.14in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666">Rightsholder </span></SPAN><br/></div>
<div style="position:absolute;top:11.20in;left:3.97in;width:1.10in;line-height:0.14in;"><DIV style="position:relative; left:0.63in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666">Validated</span><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:11.44in;left:4.17in;width:0.68in;height:0.68in" src="ci_74.png" />
<img style="position:absolute;top:10.98in;left:6.32in;width:1.62in;height:0.19in" src="ci_75.png" />
<img style="position:absolute;top:10.98in;left:6.32in;width:1.62in;height:0.19in" src="ci_76.png" />
<img style="position:absolute;top:11.17in;left:6.32in;width:1.62in;height:0.19in" src="ci_77.png" />
<img style="position:absolute;top:11.17in;left:6.32in;width:1.62in;height:0.19in" src="ci_78.png" />
<div style="position:absolute;top:10.98in;left:6.67in;width:1.10in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Copperplate;color:#ffffff">verification</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Copperplate;color:#ffffff"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.19in;left:6.55in;width:1.33in;line-height:0.14in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666">Licensed </span></SPAN><br/></div>
<div style="position:absolute;top:11.19in;left:6.55in;width:1.33in;line-height:0.14in;"><DIV style="position:relative; left:0.43in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666">Appraiser’s </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.19in;left:6.55in;width:1.33in;line-height:0.14in;"><DIV style="position:relative; left:0.98in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666">Re</span></SPAN></DIV><br/></div>
<div style="position:absolute;top:11.19in;left:6.55in;width:1.33in;line-height:0.14in;"><DIV style="position:relative; left:1.11in;"><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666">port</span><span style="font-style:italic;font-weight:normal;font-size:8pt;font-family:Bell MT;color:#666666"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:12.11in;left:6.42in;width:1.45in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">Highest</span></SPAN><br/></div>
<div style="position:absolute;top:12.11in;left:6.42in;width:1.45in;line-height:0.14in;"><DIV style="position:relative; left:0.35in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.11in;left:6.42in;width:1.45in;line-height:0.14in;"><DIV style="position:relative; left:0.38in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">Class</span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.11in;left:6.42in;width:1.45in;line-height:0.14in;"><DIV style="position:relative; left:0.61in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057"> </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.11in;left:6.42in;width:1.45in;line-height:0.14in;"><DIV style="position:relative; left:0.64in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">Valuation </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.11in;left:6.42in;width:1.45in;line-height:0.14in;"><DIV style="position:relative; left:1.11in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057">Report</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:11.44in;left:6.80in;width:0.68in;height:0.68in" src="ci_79.png" />
<img style="position:absolute;top:10.98in;left:0.87in;width:0.39in;height:0.39in" src="ci_80.png" />
<img style="position:absolute;top:10.98in;left:0.87in;width:0.39in;height:0.39in" src="ci_81.png" />
<div style="position:absolute;top:11.05in;left:0.99in;width:0.25in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:15pt;font-family:Copperplate;color:#092e5b">1</span><span style="font-style:normal;font-weight:normal;font-size:15pt;font-family:Copperplate;color:#092e5b"> </span><br/></SPAN></div>
<img style="position:absolute;top:10.98in;left:3.50in;width:0.39in;height:0.39in" src="ci_82.png" />
<img style="position:absolute;top:10.98in;left:3.50in;width:0.39in;height:0.39in" src="ci_83.png" />
<div style="position:absolute;top:11.05in;left:3.62in;width:0.25in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:15pt;font-family:Copperplate;color:#666666">2</span><span style="font-style:normal;font-weight:normal;font-size:15pt;font-family:Copperplate;color:#666666"> </span><br/></SPAN></div>
<img style="position:absolute;top:10.98in;left:6.12in;width:0.39in;height:0.39in" src="ci_84.png" />
<img style="position:absolute;top:10.98in;left:6.12in;width:0.39in;height:0.39in" src="ci_85.png" />
<div style="position:absolute;top:11.05in;left:6.24in;width:0.25in;line-height:0.25in;"><span style="font-style:normal;font-weight:normal;font-size:15pt;font-family:Copperplate;color:#666666">3</span><span style="font-style:normal;font-weight:normal;font-size:15pt;font-family:Copperplate;color:#666666"> </span><br/></SPAN></div>
<img style="position:absolute;top:11.13in;left:2.76in;width:0.67in;height:0.13in" src="ci_86.png" />
<img style="position:absolute;top:11.13in;left:5.38in;width:0.67in;height:0.13in" src="ci_87.png" />
<img style="position:absolute;top:0.38in;left:3.01in;width:3.00in;height:0.55in" src="ci_88.png" />
<img style="position:absolute;top:0.51in;left:3.23in;width:2.57in;height:0.27in" src="ci_89.png" />
<div style="position:absolute;top:10.15in;left:1.90in;width:1.31in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Reg. </span></SPAN><br/></div>
<div style="position:absolute;top:10.15in;left:1.90in;width:1.31in;line-height:0.16in;"><DIV style="position:relative; left:0.26in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">No </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:1.90in;width:1.31in;line-height:0.16in;"><DIV style="position:relative; left:0.46in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">6055547216-2</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.15in;left:3.38in;width:1.65in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Date </span></SPAN><br/></div>
<div style="position:absolute;top:10.15in;left:3.38in;width:1.65in;line-height:0.16in;"><DIV style="position:relative; left:0.28in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">of </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:3.38in;width:1.65in;line-height:0.16in;"><DIV style="position:relative; left:0.42in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">valuation: </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:3.38in;width:1.65in;line-height:0.16in;"><DIV style="position:relative; left:0.96in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">July </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:3.38in;width:1.65in;line-height:0.16in;"><DIV style="position:relative; left:1.20in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">7, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:3.38in;width:1.65in;line-height:0.16in;"><DIV style="position:relative; left:1.33in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">2021</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.15in;left:5.25in;width:1.92in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Valuation </span></SPAN><br/></div>
<div style="position:absolute;top:10.15in;left:5.25in;width:1.92in;line-height:0.16in;"><DIV style="position:relative; left:0.52in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">valid </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:5.25in;width:1.92in;line-height:0.16in;"><DIV style="position:relative; left:0.81in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">till: </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:5.25in;width:1.92in;line-height:0.16in;"><DIV style="position:relative; left:1.02in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">October </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:5.25in;width:1.92in;line-height:0.16in;"><DIV style="position:relative; left:1.48in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">7, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.15in;left:5.25in;width:1.92in;line-height:0.16in;"><DIV style="position:relative; left:1.61in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">2021</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:12.35in;left:3.91in;width:1.27in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Copperplate;color:#092e5b">page </span></SPAN><br/></div>
<div style="position:absolute;top:12.35in;left:3.91in;width:1.27in;line-height:0.21in;"><DIV style="position:relative; left:0.52in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Copperplate;color:#092e5b">2 </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.35in;left:3.91in;width:1.27in;line-height:0.21in;"><DIV style="position:relative; left:0.73in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Copperplate;color:#092e5b">of </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:12.35in;left:3.91in;width:1.27in;line-height:0.21in;"><DIV style="position:relative; left:1.06in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Copperplate;color:#092e5b">3</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:Copperplate;color:#092e5b"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:9.89in;left:1.09in;width:6.84in;height:0.22in" src="ci_90.png" />
<div style="position:absolute;top:9.80in;left:1.21in;width:0.20in;line-height:0.19in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Amiri;color:#093057">16</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.75in;left:1.53in;width:2.20in;line-height:0.21in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#093057">Average </span></SPAN><br/></div>
<div style="position:absolute;top:9.75in;left:1.53in;width:2.20in;line-height:0.21in;"><DIV style="position:relative; left:0.61in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#093057">Value </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:9.75in;left:1.53in;width:2.20in;line-height:0.21in;"><DIV style="position:relative; left:1.05in;"><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#093057">(UNIVERSAL):</span><span style="font-style:normal;font-weight:bold;font-size:11pt;font-family:Amiri;color:#093057"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">LONDON-RATE </span></SPAN><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:0.94in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">International </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:1.65in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Ofce </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:1.99in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">of </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:2.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Online </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:2.53in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">IP_Valuation </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:3.23in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">is </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:3.35in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">a </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:3.44in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">brand </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:3.78in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">name </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:4.10in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">of </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:4.24in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">product </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:4.68in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">of </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:4.82in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Brit </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:5.06in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Management </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:5.77in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Consultants </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:6.42in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Ltd. </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:6.66in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">(BMC </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.33in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:7.03in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Company),</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:1.37in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Address: </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:1.84in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">The </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:2.08in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Gridiron </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:2.58in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Building, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:3.08in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Pancras </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:3.51in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Square, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:3.92in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">London, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:4.39in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">UK, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:4.63in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">N1C </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:4.92in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">4AG, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.46in;left:0.69in;width:7.65in;line-height:0.16in;"><DIV style="position:relative; left:5.23in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">www.londonrate.org</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">The </span></SPAN><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:0.24in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">authenticity </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:0.89in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">of </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:1.03in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">present </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:1.45in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Valuation </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:1.98in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">Certifcate </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:2.55in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">could </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:2.88in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">be </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:3.03in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">checked </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:3.49in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">by </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:3.65in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">scanning </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:4.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">following </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.59in;left:1.95in;width:5.16in;line-height:0.16in;"><DIV style="position:relative; left:4.66in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a">QR-code</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Amiri;color:#1a1a1a"> </span><br/></SPAN></DIV></div>
</body>
</html>
