 <div class="bread-main">
        <!-- Navbar Start -->
            <?php require 'main-navbar.php'; ?>
        <!-- Navbar End -->

        <div class="bread-content container">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="<?php echo base_url('/');?>">Home</a></li>
                        <li class="breadcrumb-item active">Why Us</li>
                      </ol>
                    </nav>

                    <h1>Why IP-Valuation?</h1>

                </div>
            </div>

        </div>
    </div>



    <main class="main-padding">
        <div class="container">
            <div class="row ">
                <div class="col-12">
                    <h3 class="mb-5 fw-bold">Why IP-Valuation?</h3>

                    <p>Global economic environment is changing towards the creation of new business models and management strategies where IP assets are an essential core of building the company and brand value is becoming a benchmark for potential companies’ growth. Knowledge of the high value and contribution of IP assets, the linkages between them are essential for business strategy, IP management and IP valuation.</p>

                    <p>Nowadays, stiff competition and the competitive advantage attribute to the development, integration and reconfiguration of intangible resources. Yet, very few companies have the knowledge of the potential value and benefits that lie within their IP assets.</p>

                    <p>Intellectual Property valuation helps companies to determine the true value of their business and conduct capitalization strategies on the assets that they possess. In business terms, IP-Valuation assesses the monetary value of an IP asset. It is estimated that approximately each company has two-thirds of companies (business) assets that are potentially eligible for Intellectual Property protections and the advantages they entail.</p>

                    <p>IP-Valuation is very essential for business planning, carrying certain business strategies, for joint ventures, for licensing, M&A, sales purchase transactions, investments and loans. Although securitization of loan transactions with IP assets is not currently widely practiced, there is already a great deal of interest in this subject in the accounting and financial institutions and communities.</p>

                    <p>Even if IP securitization of loans is not commonly practiced, it is obvious that the quality and quantity of IP assets are taken into consideration when investment decisions are made. A strong IP asset portfolio that is well integrated into a company business plan will be attractive to an investor due to the potential revenues generated by the IP. Moreover, investors will positively consider the fact that development of IP assets shows a commitment to innovation and product enhancement.</p>

                    <p>Other benefits that can be gained by conducted IP-Valuation are:</p>

                    <ul class="unstyled_list  bullet-points">
                        <li>Determination of the value of the contribution to the authorized capital (fund);</li>
                        <li>Inventory and introduction of intangible assets into economic circulation;</li>
                        <li>Optimization of taxation;</li>
                        <li>In a bankruptcy procedure, the IP assets of the bankrupt company have to be valued, as also its physical assets, in determining how those are assets are to be distributed;</li>

                        <li>Issuance of a loan secured by exclusive rights;</li>
                        <li>Attracting investors;</li>
                        <li>Estimation and determination of a target price prior to negotiations for purchasing an IP asset;</li>
                        <li>Resolution of conflicts, including in the event of damages due to violations of exclusive rights to intangible assets;</li>
                        <li>Assignment of rights to an intangible asset or issuance of licenses for their use</li>
                        <li>Assignment of rights to an intangible asset or issuance of licenses for their use</li>
                        <li>Establishing the cost of the license;</li>
                        <li>Determination of the profit share;</li>
                        <li>Calculation of amounts of royalty payments.</li> 
                    </ul>

                    <p>When evaluating intellectual property, several methods of determining value are applied:</p>

                    <ul class="unstyled_list bullet-points">
                        <li>costly way</li>
                        <li>comparative method</li>
                        <li>discounting future income</li>
                    </ul>
                </div>
            </div>
        </div>
    </main>